<template>
    <div id="anime_rank">
        <h4 class="ui horizontal divider header"><i class="tag icon"></i> Description </h4>
        <p>
            This is a anime rank base on data of bangumi(bgm), animenewsnetwork(ann) and animesachi(sati).
            <br> Data generated by program. Please leave a message if wrong.
            <br> Last updated on {{ updated_date }}
        </p>

        <h4 class="ui horizontal divider header"><i class="bar chart icon"></i> Rank </h4>

        <div class="ui active large text loader" v-show="loading">Loading...</div>

        <table class="ui unstackable selectable blue very basic large table" id="anime_rank" style="display: none;" v-show="!loading">
            <thead>
                <tr>
                    <th class="one wide center aligned">Rank</th>
                    <th class="seven wide" data-content="点击标题可以查看详情" v-popup>Title</th>
                    <th class="two wide" data-content="Rate=(BGM+ANN+SATI)/3" v-popup>Rate</th>
                    <th class="two wide" data-title="从Bangumi得到分数" data-content="分数(网站排行),评价少于200非有效" v-popup>
                        <a href="http://bgm.tv" target="_blank">BGM</a>
                    </th>
                    <th class="two wide" data-title="从AnimeNewsNetwork得到分数" data-content="分数(网站排行),评价少于150非有效" v-popup>
                        <a href="http://animenewsnetwork.com" target="_blank">ANN</a>
                    </th>
                    <th class="two wide" data-title="从AnimeSachi得到分数" data-content="分数(网站排行),评价少于20非有效" v-popup>
                        <a href="http://animesachi.com" target="_blank">SATI</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="anime in rank_show" track-by="rank">
                    <td class="center aligned">{{ anime.rank }}</td>
                    <td><a v-on:click.prevent="showDetail(anime)" href="javascript:void(0)">{{ anime.name_cn }}</a></td>
                    <td style="color: teal;" v-bind:class="{'top': anime.rank <= 10}">{{ anime.score }}</td>
                    <td v-bind:class="{'disabled' : anime.bgm_score == 0, 'top': anime.bgm_score_rank <= 10}" data-content="{{ anime.bgm_votes }}人投票，热度排名{{ anime.bgm_pop_rank }}"
                    v-popup>{{ anime.bgm_score }} ({{ anime.bgm_score_rank == 0 ? ' - ' : anime.bgm_score_rank }})</td>
                    <td v-bind:class="{'disabled' : anime.ann_score == 0, 'top': anime.ann_score_rank <= 10}" data-content="{{ anime.ann_votes }}人投票，热度排名{{ anime.ann_pop_rank }}"
                    v-popup>{{ anime.ann_score }} ({{ anime.ann_score_rank == 0 ? ' - ' : anime.ann_score_rank }})</td>
                    <td v-bind:class="{'disabled' : anime.sati_score == 0, 'top': anime.sati_score_rank <= 10}" data-content="{{ anime.sati_votes }}人投票，热度排名{{ anime.sati_pop_rank }}"
                    v-popup>{{ anime.sati_score }} ({{ anime.sati_score_rank == 0 ? ' - ' : anime.sati_score_rank }})</td>
                </tr>

                <tr class="positive" v-if="hasMore">
                    <td class="selectable positive center aligned" colspan="6">
                        <a v-on:click.prevent="showAll">Show All</a>
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="ui small modal" id="detail">
            <i class="close icon"></i>
            <div class="ui blue header">
                {{ detail.loading ? 'Loading..' : 'Rank ' + detail.show_rank }}
                <span class="ui teal right floated segment" style="color: teal;" v-if="!detail.loading">{{ rank[detail.show_rank - 1].score }}</span>
            </div>
            <!--<div class="content" v-show="detail.loading">
                <div class="ui icon message">
                    <i class="notched circle loading icon"></i>
                    <div class="content">
                        <div class="header">稍候 </div>
                        <p>正在加载</p>
                    </div>
                </div>
            </div>-->
            <div class="image content">
                <!--<div class="ui rounded image" style="min-width: 260px;" @click="test">
                    <img id="detailImage" class="ui image" style="margin: auto" src="build/placeholder.png">
                </div>-->
                <div class="description">
                    <div class="ui header">Title</div>
                    <p>{{ detail.data.name_jp }} (Japnese)</p>
                    <p>{{ detail.data.name_cn }} (Chinese)</p>
                    <p>{{ detail.data.name_en }} (English)</p>
                    <div class="ui header">Info</div>
                    <p>{{ detail.data.type }}
                        <span>{{ detail.data.eps == 0 ? '' : detail.data.eps + '话　' }}</span> {{ detail.data.air_date }}
                        放送
                    </p>
                    <div class="ui header">User Ratings</div>
                    <table class="ui unstackable very basic table">
                        <thead>
                            <tr>
                                <th>Link</th>
                                <th>Rate</th>
                                <th>Rank</th>
                                <th>Votes</th>
                                <th>Rank Pop</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><a href="{{ detail.data.bgm_url }}" target="_blank">BGM</a></td>
                                <td>{{ rank[detail.show_rank - 1].bgm_score }}</td>
                                <td>{{ rank[detail.show_rank - 1].bgm_score_rank }}</td>
                                <td>{{ rank[detail.show_rank - 1].bgm_votes }}</td>
                                <td>{{ rank[detail.show_rank - 1].bgm_pop_rank }}</td>
                            </tr>
                            <tr>
                                <td><a href="{{ detail.data.ann_url }}" target="_blank">ANN</a></td>
                                <td>{{ rank[detail.show_rank - 1].ann_score }}</td>
                                <td>{{ rank[detail.show_rank - 1].ann_score_rank }}</td>
                                <td>{{ rank[detail.show_rank - 1].ann_votes }}</td>
                                <td>{{ rank[detail.show_rank - 1].ann_pop_rank }}</td>
                            </tr>
                            <tr>
                                <td><a href="{{ detail.data.sati_url }}" target="_blank">SATI</a></td>
                                <td>{{ rank[detail.show_rank - 1].sati_score }}</td>
                                <td>{{ rank[detail.show_rank - 1].sati_score_rank }}</td>
                                <td>{{ rank[detail.show_rank - 1].sati_votes }}</td>
                                <td>{{ rank[detail.show_rank - 1].sati_pop_rank }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    module.exports = {
        el: function() { return '#anime_rank'},
        
        props: ['keyword'],
        
        data: function() {
            return {
                loading: true,
                hasMore: false,
                rank: [],
                rank_filter: [],
                rank_show: [],
                updated_date: '0000-00-00',

                detail: {
                    loading: true,
                    show_rank: 0,
                    data: {}
                }
            }
        },

        compiled: function () {
            $.ajax({
                url: 'http://api.frezc.com/anime_rank?limit=1200',
                context: this,
                success: function (data) {
                    for (var i = 0; i < data.rank.length; i++) {
                        data.rank[i].rank = i + 1
                    }
                    this.rank = data.rank
                    this.rank_filter = this.rank
                    this.rank_show = this.rank.slice(0, 50)
                    this.updated_date = data.updated_date
                    this.loading = false
                    this.hasMore = false
                }
            });
            
            self = this;
            $(window).scroll(function () {
                if ($(window).scrollTop() == $(document).height() - $(window).height()) {
                    self.loadMore();
                }
            });
        },

        methods: {
            loadMore: function () {
                if (!this.loading) {
                    var offset = this.rank_show.length;
                    var add = this.rank_filter.slice(offset, offset+50);
                    for(var i=0; i<add.length; i++){
                        this.rank_show.push(add[i]);
                    }
                }
            },

            showAll: function (event) {
                this.rank_show = this.rank

                this.hasMore = false
            },

            search: function (val, oldVal) {
                this.rank_filter = this.rank.filter(function (anime) {
                    return anime.name_cn.match(new RegExp(val, 'i'))
                })
                this.rank_show = this.rank_filter.slice(0, 50)
            },

            showDetail: function (anime) {
                this.showDetailModal();
                if (anime.rank != this.detail.show_rank) {
                    this.detail.loading = true;
                    $('#detailImage').attr('src', "build/placeholder.png");
                    $.ajax({
                        url: 'http://api.frezc.com/relate_info/' + anime.relate_id,
                        context: this,
                        success: function (data) {
                            data.ann_url = data.ann_url.split(',')[0];
                            data.bgm_url = data.bgm_url.split(',')[0];
                            data.sati_url = data.sati_url.split(',')[0];
                            
                            this.detail.show_rank = anime.rank;
                            this.detail.data = data;
                            this.detail.loading = false;
                            
                            /*
                            $('#detailImage').load(data.image, function (response, status, xhr) {
                                console.log(response)
                                console.log(status)
                                console.log(xhr)
                                // if (status == "success")
                                //     this.attr('src', )
                                // if (status == "error")
                                //     this.addClass('disabled');
                            });*/
                        }
                    });
                }
            },

            asyncLoadImage: function (url, callback) {
                var img = new Image(); //创建一个Image对象，实现图片的预下载 
                img.src = url;

                if (img.complete) { // 如果图片已经存在于浏览器缓存，直接调用回调函数 
                    callback.call(img);
                    return; // 直接返回，不用再处理onload事件 
                }

                img.onload = function () { //图片下载完毕时异步调用callback函数。 
                    callback.call(img);//将回调函数的this替换为Image对象 
                };
            },

            showDetailModal: function () {
                $('#detail')
                    .modal('setting', 'transition', 'horizontal flip')
                    .modal('show');
            }
        },
        
        watch: {
            'keyword': 'search'
        }
    }

</script>

<style>
    .top {
        font-weight: bold;
        color: darkred;
    }
</style>